import {
  Bot,
  Brain,
  ChartColumn,
  ChartLine,
  ClipboardCheck,
  Cloud,
  Code,
  Database,
  FileSearch,
  FlaskConical,
  Mail,
  MapPin,
  MessageSquareText,
  Network,
  Plug,
  ShieldCheck,
  Sparkles,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Technology names as the data spells them, mapped to simple-icons slugs.
 * Names without a published logo get a lucide icon instead, never a guessed
 * or redrawn brand mark. Pure and client safe: strings and lucide only.
 */
export const TECH_SLUG: Record<string, string> = {
  "Next.js": "nextdotjs",
  React: "react",
  "React Native": "react",
  TypeScript: "typescript",
  JavaScript: "javascript",
  HTML: "html5",
  CSS: "css",
  "Tailwind CSS": "tailwindcss",
  Bootstrap: "bootstrap",
  jQuery: "jquery",
  Vite: "vite",
  NestJS: "nestjs",
  "Node.js": "nodedotjs",
  Prisma: "prisma",
  "Drizzle ORM": "drizzle",
  Zod: "zod",
  PostgreSQL: "postgresql",
  MySQL: "mysql",
  SQLite: "sqlite",
  MongoDB: "mongodb",
  Redis: "redis",
  Supabase: "supabase",
  "Supabase Auth": "supabase",
  Firebase: "firebase",
  "PHP 8": "php",
  PHP: "php",
  WordPress: "wordpress",
  WooCommerce: "woocommerce",
  Flutter: "flutter",
  Dart: "dart",
  Android: "android",
  iOS: "apple",
  Docker: "docker",
  Kubernetes: "kubernetes",
  "Netlify Forms": "netlify",
  Netlify: "netlify",
  Vercel: "vercel",
  Git: "git",
  "GitHub Actions": "githubactions",
  "Linux administration": "linux",
  Linux: "linux",
  Bash: "gnubash",
  Python: "python",
  R: "r",
  "C++": "cplusplus",
  "C#/.NET": "dotnet",
  PyTorch: "pytorch",
  TensorFlow: "tensorflow",
  Keras: "keras",
  "scikit-learn": "scikitlearn",
  Pandas: "pandas",
  NumPy: "numpy",
  OpenCV: "opencv",
  "Hugging Face": "huggingface",
  "Google Gemini": "googlegemini",
  "Anthropic Claude": "claude",
  "Apache Airflow": "apacheairflow",
  "Apache Spark": "apachespark",
  SQLAlchemy: "sqlalchemy",
  Dask: "dask",
  Grafana: "grafana",
  Plotly: "plotly",
  MLflow: "mlflow",
  DVC: "dvc",
  BigQuery: "googlebigquery",
  "Vertex AI": "googlecloud",
  Django: "django",
  Flask: "flask",
  FastAPI: "fastapi",
  GraphQL: "graphql",
  "ELK Stack": "elasticstack",
  "Google Analytics 4": "googleanalytics",
  Spring: "spring",
};

const FALLBACK: Record<string, LucideIcon> = {
  SQL: Database,
  "SQL Server": Database,
  "OpenAI GPT": Sparkles,
  "LLM ensembles and evaluation": Bot,
  "Prompt engineering": MessageSquareText,
  RAG: FileSearch,
  XGBoost: Brain,
  LightGBM: Brain,
  BERT: Brain,
  Matplotlib: ChartLine,
  Seaborn: ChartLine,
  "Power BI": ChartColumn,
  Tableau: ChartColumn,
  "Azure AKS": Cloud,
  "Application Insights": Cloud,
  "Key Vault": Cloud,
  "AWS SageMaker": Cloud,
  S3: Cloud,
  Lambda: Cloud,
  "Experiment tracking": FlaskConical,
  "CI/CD": Plug,
  "REST APIs": Plug,
  "Network configuration": Network,
  "Firewall management": ShieldCheck,
  "ITIL practices": ClipboardCheck,
  PHPMailer: Mail,
  GPS: MapPin,
  "Mobile Money": Wallet,
  Playwright: FlaskConical,
};

export function techSlug(name: string): string | null {
  return TECH_SLUG[name] ?? null;
}

/** The lucide icon for a technology without a published logo. */
export function techFallbackIcon(name: string): LucideIcon {
  return FALLBACK[name] ?? Code;
}
