import { WORK_IMAGES } from "@/data/work-images";
import { cn } from "@/lib/utils";

interface WorkImageProps {
  slug: string;
  name: string;
  /** What the screenshot shows. Falls back to "Screenshot of <name>". */
  alt?: string;
  /** The image's rendered width per breakpoint, for the browser to pick a file. */
  sizes: string;
  /** Above the fold: load eagerly and early. */
  priority?: boolean;
  className?: string;
}

/**
 * A work screenshot as a <picture> with AVIF and WebP sources generated by
 * scripts/optimize-images.mjs. Width and height are set so nothing shifts
 * while it loads. Without a generated image it renders a quiet typographic
 * plate instead, so a page never breaks on a missing file.
 */
export function WorkImage({ slug, name, alt, sizes, priority = false, className }: WorkImageProps) {
  const image = WORK_IMAGES[slug];
  const frame = cn("border-rule bg-muted block overflow-hidden rounded-[12px] border", className);

  if (!image) {
    return (
      <div className={cn(frame, "relative aspect-[16/10]")}>
        <div aria-hidden className="absolute inset-0 flex flex-col justify-between p-5 sm:p-7">
          <span className="kicker">Project</span>
          <span className="text-ink-soft max-w-[14ch] font-serif text-[clamp(1.75rem,5vw,3.25rem)] leading-[1] tracking-[-0.015em]">
            {name}
          </span>
        </div>
        <span className="sr-only">No screenshot yet for {name}.</span>
      </div>
    );
  }

  const srcset = (ext: "avif" | "webp") => image.widths.map((w) => `${image.base}-${w}.${ext} ${w}w`).join(", ");
  const fallbackWidth = image.widths.find((w) => w >= 960) ?? image.widths[image.widths.length - 1];

  return (
    <picture className={frame}>
      <source type="image/avif" srcSet={srcset("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={srcset("webp")} sizes={sizes} />
      <img
        src={`${image.base}-${fallbackWidth}.webp`}
        alt={alt ?? `Screenshot of ${name}`}
        width={image.width}
        height={image.height}
        sizes={sizes}
        loading={priority ? "eager" : "lazy"}
        fetchPriority={priority ? "high" : "auto"}
        decoding="async"
        className="block h-auto w-full"
        style={{ backgroundImage: `url(${image.blurDataURL})`, backgroundSize: "cover" }}
      />
    </picture>
  );
}
