/**
 * Optimises the site's raster images.
 *
 * - Avatar: assets/icon-src/avatar.png (the GitHub profile photo) becomes
 *   public/images/avatar-{240,460}.{avif,webp}.
 * - Work screenshots: every assets/work-src/<slug>.png becomes
 *   public/images/work/<slug>-{640,960,1280,1600}.{avif,webp} (widths larger than the
 *   source are skipped), plus a 16 px wide blur placeholder, and the metadata is
 *   written to src/data/work-images.ts.
 *
 * Run: node scripts/optimize-images.mjs
 */
import sharp from "sharp";
import { mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const WIDTHS = [640, 960, 1280, 1600];
const AVIF = { quality: 60, effort: 6 };
const WEBP = { quality: 72, effort: 6 };

/* ---------- avatar ---------- */

const AVATAR_SRC = "assets/icon-src/avatar.png";
if (existsSync(AVATAR_SRC)) {
  await mkdir("public/images", { recursive: true });
  for (const size of [240, 460]) {
    const base = sharp(AVATAR_SRC).resize(size, size, { fit: "cover", kernel: "lanczos3" });
    const avif = `public/images/avatar-${size}.avif`;
    const webp = `public/images/avatar-${size}.webp`;
    await base.clone().avif({ quality: 58, effort: 6 }).toFile(avif);
    await base.clone().webp({ quality: 78, effort: 6 }).toFile(webp);
    for (const f of [avif, webp]) console.log(`${f} ${(await stat(f)).size} B`);
  }
}

/* ---------- work screenshots ---------- */

const SRC = "assets/work-src";
const OUT = "public/images/work";
await mkdir(OUT, { recursive: true });

const sources = (await readdir(SRC)).filter((f) => f.endsWith(".png")).sort();
const slugs = new Set(sources.map((f) => f.replace(/\.png$/, "")));

// Remove generated files for screenshots that no longer have a source.
for (const f of await readdir(OUT)) {
  const slug = f.replace(/-\d+\.(avif|webp)$/, "");
  if (!slugs.has(slug)) await rm(path.join(OUT, f));
}

const entries = [];
for (const file of sources) {
  const slug = file.replace(/\.png$/, "");
  const input = path.join(SRC, file);
  const meta = await sharp(input).metadata();
  const srcW = meta.width ?? 0;
  const srcH = meta.height ?? 0;
  const widths = WIDTHS.filter((w) => w <= srcW);
  if (widths.length === 0) widths.push(srcW);

  for (const f of await readdir(OUT)) {
    if (f.startsWith(`${slug}-`) && !widths.some((w) => f === `${slug}-${w}.avif` || f === `${slug}-${w}.webp`)) {
      await rm(path.join(OUT, f));
    }
  }

  let height = srcH;
  for (const w of widths) {
    const resized = sharp(input).resize({ width: w, kernel: "lanczos3" });
    const avif = path.join(OUT, `${slug}-${w}.avif`);
    const webp = path.join(OUT, `${slug}-${w}.webp`);
    await resized.clone().avif(AVIF).toFile(avif);
    const info = await resized.clone().webp(WEBP).toFile(webp);
    height = info.height;
    console.log(`${avif} ${(await stat(avif)).size} B, ${webp} ${(await stat(webp)).size} B`);
  }

  const blur = await sharp(input).resize({ width: 16 }).webp({ quality: 40 }).toBuffer();
  entries.push({
    slug,
    base: `/images/work/${slug}`,
    widths,
    width: widths[widths.length - 1],
    height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  });
}

const body = entries
  .map(
    (e) =>
      `  ${/^[A-Za-z_$][\w$]*$/.test(e.slug) ? e.slug : JSON.stringify(e.slug)}: {\n` +
      `    base: ${JSON.stringify(e.base)},\n` +
      `    widths: [${e.widths.join(", ")}],\n` +
      `    width: ${e.width},\n` +
      `    height: ${e.height},\n` +
      `    blurDataURL:\n      ${JSON.stringify(e.blurDataURL)},\n` +
      `  },\n`
  )
  .join("");

const ts = `/**
 * Screenshot metadata for work entries, keyed by work slug. Generated by
 * scripts/optimize-images.mjs from assets/work-src; do not edit by hand.
 * Files live in public/images/work/<slug>-<width>.{avif,webp}.
 */

export interface WorkImage {
  /** Base path without width and extension, for example "/images/work/hms". */
  base: string;
  /** Widths generated for this image, ascending. */
  widths: number[];
  /** Intrinsic size of the largest generated file. */
  width: number;
  height: number;
  /** Tiny base64 placeholder shown while loading. */
  blurDataURL: string;
}

export const WORK_IMAGES: Partial<Record<string, WorkImage>> = {
${body}};
`;
await writeFile("src/data/work-images.ts", ts);
console.log(`wrote src/data/work-images.ts (${entries.length} entries)`);
