/**
 * Facts about the owner, used across the portfolio, blog, metadata and legal
 * pages. Sources: the GitHub profile README (AshabaJasper/AshabaJasper) and
 * the owner's answers on 7 October 2026, and his CV (last updated June 2026). Nothing here is invented: unknown
 * values stay null and are listed as launch blockers in the checklist.
 */

export const profile = {
  /** How the name appears in the header and titles. */
  name: "Ashaba Jasper",
  /** Full legal name, used on legal pages and in structured data. */
  fullName: "Ashaba Joshua Jasper",
  role: "Software engineer and data scientist",
  /** The CV's headline roles. */
  headline: "Data Scientist, AI/ML Engineer, Full-Stack Developer",
  location: "Kampala, Uganda",
  heroLine:
    "Software engineer and data scientist in Kampala, building data, AI and business systems for East African organisations.",
  about:
    "I design and build practical systems end to end: data pipelines and models, REST APIs and full-stack web applications, for businesses, co-operatives and non-profits.",
  email: "ashabajasper@gmail.com",
  currently: [
    {
      name: "Persmon Technologies",
      role: "Co-founder and COO",
      description: "A Kampala software company with 47 shipped projects, from hotel systems to civic data.",
      href: "https://persmontechnologies.com",
    },
    {
      name: "Learnnovate",
      role: "Founder and Program Director",
      description: "A non-profit that teaches technology skills.",
      href: "https://github.com/Learnnovate-Africa",
    },
  ],
  education: {
    degree: "BSc Computer Science, First Class Honours",
    gpa: "4.62/5.0",
    school: "Uganda Christian University",
  },
  exploring: ["MLOps", "Data engineering", "Production-grade applied AI"],
  links: {
    github: "https://github.com/AshabaJasper",
    linkedin: "https://www.linkedin.com/in/ashaba-jasper-joshua/",
    x: "https://x.com/ashaba_jasper",
    googleDevelopers: "https://g.dev/ashaba_jasper",
  },
  /** Served from public/images; generated by scripts/optimize-images.mjs from the GitHub avatar. */
  avatar: {
    src: "/images/avatar-460.webp",
    width: 460,
    height: 460,
    alt: "Portrait of Ashaba Jasper",
  },
  xHandle: "@ashaba_jasper",
} as const;

export type Profile = typeof profile;
