/**
 * Screenshot metadata for work entries, keyed by work slug. Generated by
 * scripts/optimize-images.mjs from assets/work-src; do not edit by hand.
 * Files live in public/images/work/<slug>-<width>.{avif,webp}.
 */

export interface WorkImage {
  /** Base path without width and extension, for example "/images/work/hms". */
  base: string;
  /** Widths generated for this image, ascending. */
  widths: number[];
  /** Intrinsic size of the largest generated file. */
  width: number;
  height: number;
  /** Tiny base64 placeholder shown while loading. */
  blurDataURL: string;
}

export const WORK_IMAGES: Partial<Record<string, WorkImage>> = {
  hms: {
    base: "/images/work/hms",
    widths: [640, 960, 1280, 1600],
    width: 1600,
    height: 1000,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAoAA4BaJYgCdAEHHlxEYAD+9CU/uLpFYs+bbdjGMV9TVhhUAF0s/pdNn0t2B1RLQIPvivIMwAAA",
  },
  "jasper-os": {
    base: "/images/work/jasper-os",
    widths: [640, 960, 1280, 1600],
    width: 1600,
    height: 1000,
    blurDataURL:
      "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAABwAQCdASoQAAoAA4BaJaWZAAGIAAD+9EZOnd0LvJphAAAA",
  },
  oms: {
    base: "/images/work/oms",
    widths: [640, 960, 1280, 1600],
    width: 1600,
    height: 1000,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQAAoAA4BaJZACdADbH+qoAP7y/fxlb/XoEQqqix1Figv1T6TMeSoeH+fdcNLynEAAAA==",
  },
  "pearl-insights": {
    base: "/images/work/pearl-insights",
    widths: [640, 960, 1280, 1600],
    width: 1600,
    height: 1000,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAoAA4BaJQBYdiIZsua4raHAAP7c/cOzdCTMnoUnzCWSC/1lpldg+AtPP6XLtlCdosKaZJ4kBsUt6gxrkcoWH7/Mz5s6SM+TrflIRNIewAAA",
  },
  "sickle-cell-awards-voting": {
    base: "/images/work/sickle-cell-awards-voting",
    widths: [640, 960, 1280, 1600],
    width: 1600,
    height: 1000,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAoAA4BaJZQAAudiDfR1w8AA/vI+Do5TquhfAq7Hk3bvzxzWGxJD13EwFBTKhMB01s1Wby3A9SQ6Pc6begAA",
  },
  "uganda-bookshop": {
    base: "/images/work/uganda-bookshop",
    widths: [640, 960, 1280, 1600],
    width: 1600,
    height: 1000,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAoAA4BaJZQCdAEPSqIrGNgAAP72CW8W8yLJTLwETvxk6jxhE6u+MdJbEFlWDVQa0VjpkyDtQ9eGx4nrS0pORNTigAAA",
  },
};
