/**
 * Screenshot metadata for work entries, keyed by work slug. Generated by
 * scripts/optimize-images.mjs from assets/work-src; do not edit by hand.
 * Files live in public/images/work/<slug>-<width>.{avif,webp}.
 */

export interface WorkImage {
  /** Base path without width and extension, for example "/images/work/hms". */
  base: string;
  /** Widths generated for this image, ascending. */
  widths: number[];
  /** Intrinsic size of the largest generated file. */
  width: number;
  height: number;
  /** Tiny base64 placeholder shown while loading. */
  blurDataURL: string;
}

export const WORK_IMAGES: Partial<Record<string, WorkImage>> = {};
